language: cpp
sudo    : required
dist    : Trusty
group   : stable
compiler: gcc
os      : linux

services:
- docker

install:
- sudo apt-get install libgtest-dev

script:
- export WORKDIR=$PWD
- echo $PWD
- cd /usr/src/gtest
- ls -al
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd ${WORK_DIR}

before_install:
- echo $LANG
- chmod +x ./scripts/dependencies.sh ./scripts/build.sh ./scripts/docker_exec.sh extract-qt-installer
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/dependencies.sh; fi
before_script:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/docker_exec.sh "./scripts/build.sh"; fi
after_success:
branches:
  only:
  - master
notifications:
  email: false
env:
  global:
  - LANG="en_US.UTF-8"
