language: cpp
sudo    : required
dist    : Trusty
group   : stable
compiler: gcc
os      : linux

install:
- sudo apt-get install libgtest-dev

script:
- export WORKDIR=$PWD
- echo $PWD
- cd /usr/src/gtest
- ls -al
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd ${WORKDIR}
- chmod +x ./scripts/dependencies.sh ./scripts/build.sh ./scripts/qt-5.7 ./scripts/extract-qt-installer
- ./scripts/dependencies.sh
- source ./scripts/qt-5.7.env
- ./scripts/build.sh

notifications:
  email: false
env:
  global:
  - LANG="en_US.UTF-8"
