language: cpp
sudo    : required
dist    : Trusty
group   : stable
compiler: gcc
os      : linux

services:
- docker

env:
- QT_VERSION=qt:5.7.0

before_install:
- echo $LANG
- chmod +x ./scripts/dependencies.sh ./scripts/build.sh
# - if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/dependencies.sh; fi
before_script:
- docker_exec.sh "qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ../iFresh/iFresh.pro && make && ./iFresh"
# - if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/build.sh; fi
after_success:
branches:
  only:
  - master
notifications:
  email: false
env:
  global:
  - LANG="en_US.UTF-8"
