language: cpp
sudo    : required
dist    : precise
group   : stable
compiler: gcc
os      : linux

matrix:
  include:
    - compiler: gcc
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-5
       env: COMPILER=g++-5

before_install:
- echo $LANG
- chmod +x ./scripts/dependencies.sh ./scripts/build.sh
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/dependencies.sh; fi
before_script:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/build.sh; fi
after_success:
branches:
  only:
  - master
notifications:
  email: false
env:
  global:
  - LANG="en_US.UTF-8"
